server:
  port: 8080
  servlet:
    context-path: /api
spring:
  session:
    timeout: 86400
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field:  is_deleted
      logic-delete-value:  1
      logic-not-delete-value: 0

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://service-django