server:
  port: 8080
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/test
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
